# Generated by Django 4.2.23 on 2025-07-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_orderitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
